[general]
import = ["~/.config/alacritty/themes/fog-and-ember.toml"]

[env]
TERM = "alacritty"

[window]
dynamic_title = true
opacity = 0.90
title = "Alacritty"
padding = { x = 12, y = 8 }

[window.class]
general = "Alacritty"
instance = "Alacritty"

[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

[scrolling]
history = 50000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"
