#!/usr/bin/env bash
set -euo pipefail

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
hypr_dir="$config_home/hypr"
palette="$hypr_dir/palette.conf"
reload=true
[[ ${1:-} == "--no-reload" ]] && reload=false

# shellcheck source=/dev/null
source "$palette"

for key in BASE SURFACE SURFACE2 TEXT MUTED ACCENT ACCENT2 CPU MEMORY BLUETOOTH VPN_IDLE AUDIO HEADSET NETWORK SUCCESS WARNING CRITICAL; do
  value=${!key:-}
  if [[ ! $value =~ ^[0-9A-Fa-f]{6}$ ]]; then
    printf 'Invalid palette value: %s=%s\n' "$key" "$value" >&2
    exit 1
  fi
done

mkdir -p "$config_home/waybar" "$config_home/rofi" "$config_home/mako"

{
  printf '%s\n' '-- Generated by scripts/sync-theme.sh. Edit palette.conf, not this file.'
  printf '%s\n' 'THEME = {'
  printf '  base = "rgb(%s)",\n' "$BASE"
  printf '  surface = "rgb(%s)",\n' "$SURFACE"
  printf '  surface2 = "rgb(%s)",\n' "$SURFACE2"
  printf '  text = "rgb(%s)",\n' "$TEXT"
  printf '  muted = "rgb(%s)",\n' "$MUTED"
  printf '  accent = "rgb(%s)",\n' "$ACCENT"
  printf '  accent2 = "rgb(%s)",\n' "$ACCENT2"
  printf '  success = "rgb(%s)",\n' "$SUCCESS"
  printf '  warning = "rgb(%s)",\n' "$WARNING"
  printf '  critical = "rgb(%s)",\n' "$CRITICAL"
  printf '  inactive = "rgba(%s66)",\n' "$MUTED"
  printf '  shadow = "rgba(07090dcc)",\n'
  printf '%s\n' '}'
} >"$hypr_dir/generated-theme.lua"

{
  printf '@define-color base #%s;\n' "$BASE"
  printf '@define-color surface #%s;\n' "$SURFACE"
  printf '@define-color surface2 #%s;\n' "$SURFACE2"
  printf '@define-color text #%s;\n' "$TEXT"
  printf '@define-color muted #%s;\n' "$MUTED"
  printf '@define-color accent #%s;\n' "$ACCENT"
  printf '@define-color accent2 #%s;\n' "$ACCENT2"
  printf '@define-color cpu #%s;\n' "$CPU"
  printf '@define-color memory #%s;\n' "$MEMORY"
  printf '@define-color bluetooth #%s;\n' "$BLUETOOTH"
  printf '@define-color vpn_idle #%s;\n' "$VPN_IDLE"
  printf '@define-color audio #%s;\n' "$AUDIO"
  printf '@define-color headset #%s;\n' "$HEADSET"
  printf '@define-color network #%s;\n' "$NETWORK"
  printf '@define-color success #%s;\n' "$SUCCESS"
  printf '@define-color warning #%s;\n' "$WARNING"
  printf '@define-color critical #%s;\n' "$CRITICAL"
} >"$config_home/waybar/colors.css"

{
  printf '%s\n' '* {'
  printf '  base: #%s;\n' "$BASE"
  printf '  base-alpha: #%sf5;\n' "$BASE"
  printf '  surface: #%s;\n' "$SURFACE"
  printf '  surface-alpha: #%seb;\n' "$SURFACE"
  printf '  surface2: #%s;\n' "$SURFACE2"
  printf '  text: #%s;\n' "$TEXT"
  printf '  muted: #%s;\n' "$MUTED"
  printf '  accent: #%s;\n' "$ACCENT"
  printf '  accent2: #%s;\n' "$ACCENT2"
  printf '  accent-soft: #%s29;\n' "$ACCENT"
  printf '  border: #%s4d;\n' "$MUTED"
  printf '  success: #%s;\n' "$SUCCESS"
  printf '  warning: #%s;\n' "$WARNING"
  printf '  critical: #%s;\n' "$CRITICAL"
  printf '%s\n' '}'
} >"$config_home/rofi/fog-and-ember-colors.rasi"

{
  printf 'background-color=#%sf5\n' "$BASE"
  printf 'text-color=#%s\n' "$TEXT"
  printf 'border-color=#%s\n' "$SURFACE2"
  printf 'progress-color=over #%s\n' "$ACCENT"
  printf '%s\n' '[urgency=low]'
  printf 'border-color=#%s\n' "$MUTED"
  printf '%s\n' '[urgency=normal]'
  printf 'border-color=#%s\n' "$SURFACE2"
  printf '%s\n' '[urgency=critical]'
  printf 'border-color=#%s\n' "$CRITICAL"
  printf '%s\n' 'default-timeout=0'
} >"$config_home/mako/colors"

hyprlock_template="$hypr_dir/hyprlock.conf.template"
if [[ -f $hyprlock_template ]]; then
  hyprlock_tmp=$(mktemp "$hypr_dir/hyprlock.conf.XXXXXX")
  trap 'rm -f "$hyprlock_tmp"' EXIT
  sed \
    -e "s/@BASE@/$BASE/g" \
    -e "s/@SURFACE@/$SURFACE/g" \
    -e "s/@SURFACE2@/$SURFACE2/g" \
    -e "s/@TEXT@/$TEXT/g" \
    -e "s/@MUTED@/$MUTED/g" \
    -e "s/@ACCENT@/$ACCENT/g" \
    -e "s/@ACCENT2@/$ACCENT2/g" \
    -e "s/@SUCCESS@/$SUCCESS/g" \
    -e "s/@WARNING@/$WARNING/g" \
    -e "s/@CRITICAL@/$CRITICAL/g" \
    "$hyprlock_template" >"$hyprlock_tmp"
  mv -f "$hyprlock_tmp" "$hypr_dir/hyprlock.conf"
  trap - EXIT
fi

if $reload && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
  hyprctl reload >/dev/null 2>&1 || true
  makoctl reload >/dev/null 2>&1 || true
  "$hypr_dir/scripts/launch-waybar.sh" || true
fi
