#!/usr/bin/env bash
set -Eeuo pipefail

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
hypr_dir="$config_home/hypr"
palette="$hypr_dir/palette.conf"
reload=true
[[ ${1:-} == "--no-reload" ]] && reload=false

# shellcheck source=/dev/null
source "$palette"

for key in BASE SURFACE SURFACE2 TEXT MUTED ACCENT ACCENT2 SUCCESS WARNING CRITICAL; do
  value=${!key:-}
  [[ $value =~ ^[0-9A-Fa-f]{6}$ ]] || { printf 'Invalid palette value: %s=%s\n' "$key" "$value" >&2; exit 1; }
done

mkdir -p "$config_home/waybar" "$config_home/rofi" "$config_home/mako"

cat >"$hypr_dir/generated-theme.lua" <<EOF
-- Generated by sync-theme.sh. Edit palette.conf, not this file.
THEME = {
  base = "rgb($BASE)",
  surface = "rgb($SURFACE)",
  surface2 = "rgb($SURFACE2)",
  text = "rgb($TEXT)",
  muted = "rgb($MUTED)",
  accent = "rgb($ACCENT)",
  accent2 = "rgb($ACCENT2)",
  success = "rgb($SUCCESS)",
  warning = "rgb($WARNING)",
  critical = "rgb($CRITICAL)",
  inactive = "rgba(${MUTED}66)",
  shadow = "rgba(07090dcc)",
}
EOF

cat >"$config_home/waybar/colors.css" <<EOF
@define-color base #$BASE;
@define-color surface #$SURFACE;
@define-color surface2 #$SURFACE2;
@define-color text #$TEXT;
@define-color muted #$MUTED;
@define-color accent #$ACCENT;
@define-color accent2 #$ACCENT2;
@define-color success #$SUCCESS;
@define-color warning #$WARNING;
@define-color critical #$CRITICAL;
EOF

cat >"$config_home/rofi/fog-and-ember-colors.rasi" <<EOF
* {
  base: #$BASE;
  base-alpha: #${BASE}f5;
  surface: #$SURFACE;
  surface-alpha: #${SURFACE}eb;
  surface2: #$SURFACE2;
  text: #$TEXT;
  muted: #$MUTED;
  accent: #$ACCENT;
  accent2: #$ACCENT2;
  accent-soft: #${ACCENT}29;
  border: #${MUTED}4d;
  success: #$SUCCESS;
  warning: #$WARNING;
  critical: #$CRITICAL;
}
EOF

cat >"$config_home/mako/colors" <<EOF
background-color=#${BASE}f5
text-color=#$TEXT
border-color=#$SURFACE2
progress-color=over #$ACCENT
[urgency=low]
border-color=#$MUTED
[urgency=normal]
border-color=#$SURFACE2
[urgency=critical]
border-color=#$CRITICAL
default-timeout=0
EOF

hyprlock_template="$hypr_dir/hyprlock.conf.template"
if [[ -f $hyprlock_template ]]; then
  sed \
    -e "s/@BASE@/$BASE/g" \
    -e "s/@SURFACE@/$SURFACE/g" \
    -e "s/@SURFACE2@/$SURFACE2/g" \
    -e "s/@TEXT@/$TEXT/g" \
    -e "s/@MUTED@/$MUTED/g" \
    -e "s/@ACCENT@/$ACCENT/g" \
    -e "s/@ACCENT2@/$ACCENT2/g" \
    -e "s/@SUCCESS@/$SUCCESS/g" \
    -e "s/@WARNING@/$WARNING/g" \
    -e "s/@CRITICAL@/$CRITICAL/g" \
    "$hyprlock_template" >"$hypr_dir/hyprlock.conf"
fi

if $reload && [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
  hyprctl reload >/dev/null 2>&1 || true
  makoctl reload >/dev/null 2>&1 || true
  "$hypr_dir/scripts/launch-waybar.sh" || true
fi
